---
- kind: ssistestengine.FixedIngredientValidator
  name: Header
  specs:
  - type: ssistestengine.StringMeasurementValidator
    value: HEAD
  - type: ssistestengine.StringMeasurementValidator
    value: "1"
  - type: ssistestengine.DateTimeMeasurementValidator
    format: yyyyMMddhhmmss
  - type: ssistestengine.StringMeasurementValidator
    value: US
- kind: ssistestengine.FixedIngredientValidator
  name: Detail
  numberOfRows: 3
  specs:
  - type: ssistestengine.StringMeasurementValidator
    length: 3
  - type: ssistestengine.StringMeasurementValidator
    length: 5
  - type: ssistestengine.StringMeasurementValidator
    length: 50
  - type: ssistestengine.StringMeasurementValidator
    length: 50
  - type: ssistestengine.StringMeasurementValidator
    length: 6
  - type: ssistestengine.DateTimeMeasurementValidator
    format: yyyyMMdd
  - type: ssistestengine.StringMeasurementValidator
    length: 1
  - type: ssistestengine.DateTimeMeasurementValidator
    format: yyyyMMdd
- kind: ssistestengine.FixedIngredientValidator
  name: Footer
  specs:
  - type: ssistestengine.StringMeasurementValidator
    value: TAIL
  - type: ssistestengine.StringMeasurementValidator
    value: "1"
  - type: ssistestengine.DateTimeMeasurementValidator
    format: yyyyMMddhhmmss
  - type: ssistestengine.StringMeasurementValidator
    value: US
  - type: ssistestengine.StringMeasurementValidator
    value: 003
